slack:
  Builder Tools:
    channels:
      - builder-tools-reviews
    notify:
      - builder-tools
    requireLabel: false
  FE Infra:
    channels:
      - fe-infra-reviews
    notify:
      - fe-infra
    requireLabel: false
