version: 2.1
orbs:
  shellcheck: circleci/shellcheck@2.0.0
workflows:
  ci:
    jobs:
      - integration
      - shellcheck/check:
          dir: '.'
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
jobs:
  integration:
    docker:
      - image: circleci/node:14.18-buster
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./test
      - run:
          command: npm test
          working_directory: ./test
  publish:
    docker:
      - image: cimg/base:2020.01
    working_directory: '~'
    steps:
      - checkout:
          path: hnvm
      - run:
          name: Create hnvm gzip artifact
          command: |
            tar -zcvf hnvm.tar.gz --exclude '.git/*' hnvm/
      - run:
          name: Upload hnvm gzip to Nexus
          command: |
            curl -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" --http1.1 \
            --upload-file ~/hnvm.tar.gz \
            ${NEXUS_URL}/repository/generic-local/hnvm/${CIRCLE_TAG}/hnvm.tar.gz
      - run:
          name: SHA-256
          when: on_success
          command: |
            echo "SHA-256: $(shasum --algorithm 256 hnvm.tar.gz)"
