version: 2.1
orbs:
  # Nexus orb: https://circleci.com/developer/orbs/orb/sonatype/nexus-platform-orb
  nexus: sonatype/nexus-platform-orb@1.0.28
  shellcheck: circleci/shellcheck@2.0.0
workflows:
  ci:
    jobs:
      - integration
      - shellcheck/check:
          dir: '.'
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
jobs:
  integration:
    docker:
      - image: circleci/node:14.18-buster
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./test
      - run:
          command: npm test
          working_directory: ./test
  publish:
    executor: nexus/nexus-platform-cli
    working_directory: '~'
    steps:
      - checkout:
          path: hnvm
      - run: tar -zcvf hnvm.tar.gz --exclude '.git/*' hnvm/
      # The nexus orb doesn't support source/target mappings for file publishes, so this handles
      # placing the tarball on a filepath that matches the path we want it to be hosted at
      # in Nexus itself. This is so "filename" param for publish matches the desired path in Nexus.
      - run: mkdir -p ./hnvm/${CIRCLE_TAG}
      - run: cp ./hnvm.tar.gz ./hnvm/${CIRCLE_TAG}/hnvm.tar.gz
      - nexus/install
      - nexus/publish:
          username: NEXUS_USERNAME
          password: NEXUS_PASSWORD
          serverurl: NEXUS_URL
          filename: ./hnvm/${CIRCLE_TAG}/hnvm.tar.gz
          format: raw
          repository: generic-local
          # attributes is required for the orb, even though we don't use it here
          attributes: ""
      - run:
          name: SHA-256
          when: on_success
          command: |
            echo "SHA-256: $(shasum --algorithm 256 hnvm.tar.gz)"
